apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memory-eater
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: memory-eater
    spec:
      containers:
      - name: memory-eater
        image: maho/memory_eater:0.1
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "128Mi"
