apiVersion: v1
kind: Pod
metadata:
  name: memory-eater-128
spec:
  containers:
  - name: memory-eater
    image: maho/memory_eater:0.1
    args: ["/apl/bin/memory_eater", "500", "1"]
    resources:
      requests:
        memory: "128Mi"
      limits:
        memory: "128Mi"
  restartPolicy: OnFailure


